GHA workflow migration
LLK/scratch-render pull request #1035
Opened 2023-10-04 18:01 UTC by skripted-io

### Resolves

This PR adds a GHA workflow, migrated from CCI.

### Test Coverage

I couldn't get the tests to complete using ACT but luckily they worked in the action GH runner.

~~Please note that also this workflow calls "npm publish --tag $NPM_TAG --dry-run". Once approved please remove the "--dry-run" part to test the actual deploy. Tnx!~~ fixed with a condition.

2023-10-05 20:07 UTC, cwillisf requested changes
I'd recommend updating the NPM dependency installation steps, but other than that this looks good!

2023-10-05 20:07 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +                  npm update
Oof, I didn't realize this repo still used npm install! I would fully transition to npm ci instead:
```suggestion
            - name: Install dependencies
              run: npm ci
```

2023-10-05 20:07 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +                  npm test
If you accept the `npm ci` change above, it won't be necessary here:
```suggestion
            - name: Setup & Test
              run: |
                  mkdir -p ./test/results
                  npm test
```

2023-10-05 20:07 UTC, cwillisf commented on .github/workflows/ci-cd.yml
> +                  fi
Thanks for making this easier to read!

2023-10-05 20:19 UTC, skripted-io commented
@cwillisf I didn't bother creating a new PR but added a Env based on what I saw in Ron's script and think is useful. Also noticed we aren't using a "main" but "master" branch. And apparently linting was still commented out.

2023-10-06 01:42 UTC, cwillisf approved these changes
Looks reasonable. Thanks!

2023-10-06 01:42 UTC, cwillisf commented
For reference, the commitlint thing accepts these categories:
`[build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]`
For these GHA things, you can probably "cheat" and use "ci: did a thing" for all of them unless you're specifically altering tests or docs or something :)

2023-10-13 14:54 UTC, merged